### ISSUE TITLE
@boopickleWireProtocol macro expansion error 

### ISSUE THREAD

**Issue by SemanticBeeng** [notxcain/aecor#68]
@notxcain I am getting this as soon as I add a method in my event sourced entity api returning `*Status`. The `*Status` is implemented similar to `BookingStatus` from @vpavkin 's tutorial.

The only thing I can see different is that my `*Status` is in a different sbt module than the entity.
But also tried moving it to same sbt module and getting same

Any idea of what might cause this?

```
[error] <macro>:2:4: exception during macro expansion: 
[error] org.scalameta.invariants.InvariantFailedException: invariant failed:
[error] when verifying args.length.>(1).||(args.length.==(1).&&(scala.meta.classifiers.`package`.XtensionClassifiable[scala.meta.Term](args.head)(scala.meta.Tree.classifiable[scala.meta.Term]).is[scala.meta.internal.ast.Quasi](scala.meta.internal.ast.Quasi.ClassifierClass[scala.meta.Term])))
[error] found that args.length.>(1) is false
[error] and also scala.meta.classifiers.`package`.XtensionClassifiable[scala.meta.Term](args.head)(scala.meta.Tree.classifiable[scala.meta.Term]).is[scala.meta.internal.ast.Quasi](scala.meta.internal.ast.Quasi.ClassifierClass[scala.meta.Term]) is false
[error] where args = List("status")
[error] 	at org.scalameta.invariants.InvariantFailedException$.raise(Exceptions.scala:15)
[error] 	at scala.meta.Term$Tuple$.internal$44(Trees.scala:78)
[error] 	at scala.meta.Term$Tuple$.apply(Trees.scala:75)
[error] 	at aecor.macros.BoopickleWireProtocolMacro$.$anonfun$apply$4(boopickleWireProtocol.scala:60)
[error] 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
[error] 	at scala.collection.immutable.List.foreach(List.scala:389)
[error] 	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
[error] 	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
[error] 	at scala.collection.immutable.List.map(List.scala:295)
[error] 	at aecor.macros.BoopickleWireProtocolMacro$.apply(boopickleWireProtocol.scala:58)
[error] 	at aecor.macros.boopickleWireProtocol$inline$.apply(boopickleWireProtocol.scala:16)
[error]   @boopickleWireProtocol trait Session[F[_]] {
```

**Comment by vpavkin** [comment]
@SemanticBeeng Hi.
Could you pls post source file that causes the error?

**Comment by vpavkin** [comment]
Ok, DM exchanged showed that the problem is with methods shaped the following way (with an empty param list:
```
def status(): F[Unit)
```

Quick workaround is to remove the parens. I'll try to tune the macro to handle this case properly.

@SemanticBeeng Could you please alter the ticket title (I can't)?

**Comment by SemanticBeeng** [comment]
Vladimir advised the macro crash is due to the empty parameter list in `def status() : ` below.
Fixed to make it like `def expiresIn : `

```
  def expiresIn: F[com.kse.shared.domain.TimeMs]

  def keepAlive(period: com.kse.shared.domain.TimeMs): F[Unit]

  def status(): F[domain.SessionStatus]

  def terminate(reason: String): F[Unit]
}
```

Will keep it open to fix this rough edge of the macro.
Many thanks.

**Comment by notxcain** [comment]
Actually I’d rather forbid empty params list methods at all :) They are used to mark something impure, which should not be a case.

**Comment by SemanticBeeng** [comment]
I would be perfectly okay to close, ofc.

**Comment by vpavkin** [comment]
It's more about code-style that communicates purity. Aecor calls itself `opinionated`, so I see no problem with a readable, opinionated error-message.

**Comment by notxcain** [comment]
A nice error message would be great.
